npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true

npmScopes:
  pycabbage:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: ${GITHUB_TOKEN}

yarnPath: .yarn/releases/yarn-3.5.0.cjs
